### ISSUE TITLE
No reverb sounds with m9k weapon packs and NPCs

### ISSUE THREAD

**Issue by Paradoxidus** [modusmogulus/GmodDynamicWeaponReverb#11]
Hi! I have a problem with this addon. I currently use the m9k weapon's pack with the heavy, snipers, and pistol packs. Unfortunately, when I use them, they do not make reverbs like they just make the default or vanilla sound. Additionally, it also happens with all the NPCs who use default weapons. When I hear gunfire from the distance, they have only vanilla-like sounds, nothing else. Is there a way to fix this?

**Comment by relaxtakenotes** [comment]
Oh man, haven't played GMOD in a while and you're the reason of me picking it up again. I'm going to look into these issues and return to you if I find out anything.

**Comment by relaxtakenotes** [comment]
Doesn't seem like anything is bugged, everything is working just as intended. If you could provide some video footage and your mod collection it'd be nice.

**Comment by Paradoxidus** [comment]
I am glad that you're actually picking up again with GMod! Regarding the
videos, unfortunately, I could not send the videos here as the file size
goes beyond the required size in Gmail, so I will be sharing it with you in
Google Drive. There will be two videos testing the Reverb mod. I will also
be providing some timestamps, so you would know the context about what's
going on in the two videos.

Timestamps (These are respective: the first video is the first timestamp,
while the second video provides the second timestamp)

*First Video (first_test_npc.mp4)*
*0:00 - 0:35:* In the video, I started setting up some NPCs to attack each
other. They were using vanilla weapons that are primarily used in Half-Life
2. When they attack, it seems that the gunshot sounds are still in
its vanilla version, especially the grenade explosions. *(I apologize for
the extra sounds when some of the NPCs die. Those are from the addon, which
includes modified death sounds that are humorous.) *
*0:35 - 1:04: *Afterwards, I started moving away to test the reverb of
distant gunshot sounds. It still sounded the same, personally. However, the
grenade explosions in the distance were also heard. Judging by its grenade
sounds, it does not sound like the ones from its vanilla version. Does it
sound familiar to you?
*1:04 - 1:10: *Result and end of video


*Second Video (second_test_m9k.mp4)*

*0:00 - 1:45 (basically the entire video)*: Here, I used different m9k
weapons such as the AK-47, FAMAS, and a random m9k pistol. Judging by the
sounds, I hear no difference from before I downloaded the addon.


If you have time, please check on them! Thanks!!

My gratitude to your efforts on your amazing mod,

Paradoxine
Addon Subscriber

**Comment by relaxtakenotes** [comment]
Well guess what, I stopped playing GMOD for a while again, haha. Sorry that I forget about stuff so much, I just don't find nearly as much joy in GMOD anymore.
Either way, the videos you have sent seem like they haven't been formatted properly, meaning I have no way of viewing them since there isn't even a link for them. Why are you using EMails for github, though? Kinda seems unnecessary. However I'm going to check on this thread on a daily basis now, so please send the links to those videos and I'll have a look! :)

**Comment by relaxtakenotes** [comment]
inactivity
