### ISSUE TITLE
Problem with TFA AT (insurgency)

### ISSUE THREAD

**Issue by LuchoFe** [modusmogulus/GmodDynamicWeaponReverb#15]
Hello,
I noticed that the sounds do not work with the TFA AT, can you solve this problem?
(if you need a video or other I can send it to you).

**Comment by LuchoFe** [comment]
(i use this pack: https://steamcommunity.com/sharedfiles/filedetails/?id=2710062408

**Comment by relaxtakenotes** [comment]
will be solved in v3
