### ISSUE TITLE
The 2022 update broke this addon.

### ISSUE THREAD

**Issue by Jamesinator** [modusmogulus/GmodDynamicWeaponReverb#18]
I don't know for sure, but this addon was working just fine before the update, then after it has ceased to work. I uninstalled and reinstalled and tried some other things but its still broken. Does it need an update maybe?

**Comment by Vaingald** [comment]
Huh that's strange, seems to work fine on my pc. Not extremely unexpected though as this addon is very buggy (well at least the parts ive made lol). I'll be changing some functions from global to local today and also be taking a look if there are parts that are potentially incompatible with other addons.

**Comment by Jamesinator** [comment]
> Huh that's strange, seems to work fine on my pc. Not extremely unexpected though as this addon is very buggy (well at least the parts ive made lol). I'll be changing some functions from global to local today and also be taking a look if there are parts that are potentially incompatible with other addons.

I found the addon that causes it not to work. 
https://steamcommunity.com/sharedfiles/filedetails/?id=2599597450 It's the "suppression" mod. It's a shame because this is also a very good mod I'd like to keep but I'd have to get rid of it to hear the crisp gunshot sounds. Any way you can make it so they are compatible?

**Comment by relaxtakenotes** [comment]
we'll see what we can do in the v3 branch.

**Comment by relaxtakenotes** [comment]
never mind. the suppression mod prevents any other entityfirebullet hook from working and we rely on it to detect when there's a bullet being fired. we can't do anything.

**Comment by relaxtakenotes** [comment]
never mind x2: https://www.youtube.com/watch?v=PPqOBtq2hEo
works just fine on the v3 branch without any changes
