### ISSUE TITLE
Don't use global functions for no reason

### ISSUE THREAD

**Issue by PrikolMen** [modusmogulus/GmodDynamicWeaponReverb#19]
That addon uses local variables, but something strange reason, you create only global lua functions.
That is really bad and can do errors and problems with gmod and other addons!

Your addon takes a high place in workshop, please correct this, do not make the game worse.

**Comment by Vaingald** [comment]
Thanks for pointing this out, I'll fix it for the current workshop version as well as the wip v2

**Comment by relaxtakenotes** [comment]
fixed in the old branch and is not a problem in v3
