### ISSUE TITLE
Can I help with sounds?

### ISSUE THREAD

**Issue by Kotoshmet** [modusmogulus/GmodDynamicWeaponReverb#21]
I'm an apprentice sound designer and I would like to give a hand in development of this addon.

**Comment by modusmogulus** [comment]
Sure! Ill add you on discord, haven't talked to other sound designers online yet so i'd be happy to learn new things, if theres a particular sound/sounds that you dont like on the mod theres always room for replacement

**Comment by relaxtakenotes** [comment]
accepted
