### ISSUE TITLE
Interested in helping record sounds

### ISSUE THREAD

**Issue by Desert-Punks** [modusmogulus/GmodDynamicWeaponReverb#22]
Hey, I was really impressed with the workshop build and what it promised. I have access to a directional mic and an empty range if you guys are looking for unique recordings at various distances/angles. I also just want to give feedback over discord if you guys are willing.

**Comment by relaxtakenotes** [comment]
Me and Kotoshmet are only up for it! Have to wait until modus has something to say though. He's busy and wont be available for a few days.

**Comment by modusmogulus** [comment]
Yup I came back. You're totally welcome to help us, my discord is modusmogulus#6297 if you want to join our dev discord
