### ISSUE TITLE
Reverb disappears upon dying 

### ISSUE THREAD

**Issue by DaKingOfMonkes** [modusmogulus/GmodDynamicWeaponReverb#23]
when I die, The reverb doesn't work. It just disappears. There's no lua error or anything.
Im using the CW2.0 weapons, but it also affects the hl2 weapons.

**Comment by relaxtakenotes** [comment]
What branch?

**Comment by DaKingOfMonkes** [comment]
> 

what?

**Comment by relaxtakenotes** [comment]
Ok I assume you're using the v1 branch which is abandoned. Very soon we're going to release the newest version and hopefully your issue wont persist.
