### ISSUE TITLE
Zeta players conflict/error

### ISSUE THREAD

**Issue by Luke7381** [modusmogulus/GmodDynamicWeaponReverb#25]
when a zeta shoots there weapon this error occurs
[Dynamic Weapon Reverb] lua/autorun/server/dwr_server.lua:122: attempt to call method 'GetShootPos' (a nil value)
  1. v - lua/autorun/server/dwr_server.lua:122
   2. unknown - lua/includes/modules/hook.lua:96
    3. FireBullets - [C]:-1
     4. ShootWeapon - lua/zeta/weapon_handling.lua:324
      5. FireWeapon - lua/zeta/weapon_handling.lua:340
       6. unknown - lua/zeta/state_functions.lua:750
        7. unknown - lua/entities/npc_zetaplayer.lua:1509

**Comment by relaxtakenotes** [comment]
wow whoever made that mod is a crackhead because he didn't implement the mentioned method. i'll do a workaround

**Comment by Luke7381** [comment]
> wow whoever made that mod is a crackhead because he didn't implement the mentioned method. i'll do a workaround

What do you mean?

**Comment by relaxtakenotes** [comment]
means that i pushed a fix to workshop and you should test it

**Comment by Luke7381** [comment]
> means that i pushed a fix to workshop and you should test it

Ive reported the issue to the zeta players developer and it will be fixed in the next addons update
![image](https://user-images.githubusercontent.com/48260861/187778462-630091eb-66fb-46a9-883e-8f9d252b284e.png)

**Comment by relaxtakenotes** [comment]
cool. in the meantime the mod will check if that function exists or not and if not it'll do its thing.
