### ISSUE TITLE
shooting sounds of distant enemies feeling super close

### ISSUE THREAD

**Issue by Padex98** [modusmogulus/GmodDynamicWeaponReverb#26]
whenever an enemy shoots from afar, in addition to the far away sound of the gun, there's always this other very loud sound that plays no matter the distance

**Comment by relaxtakenotes** [comment]
oh and it's a pretty realistic behaviour because sonic cracks are... well... loud.

**Comment by Padex98** [comment]
didn't know they were this loud normally! you learn something new everyday :D

**Comment by relaxtakenotes** [comment]
well take it with a grain of salt because i've never been shot before lol

**Comment by Padex98** [comment]
no worries, I watched a couple of videos and got impressed how loud it is despite being shot at from a mile away!
