### ISSUE TITLE
[IDEA] GitHub discussions

### ISSUE THREAD

**Issue by mattszymanko** [modusmogulus/GmodDynamicWeaponReverb#27]
Hello,
I've been thinking - Are you planning to open discussions here? That is, obviously not for support queries, but rather for feedback and general questions.

Let me know what you think,
Matt

**Comment by relaxtakenotes** [comment]
you may use github issues for that

**Comment by mattszymanko** [comment]
Indeed, I'm aware. But, then again, that's not really my point. My point was simply to separate problems and bugs from feedback and general talking. Still, this was just a suggestion, so no worries.

**Comment by mattszymanko** [comment]
I mean, you could simply use the issue templates, then use the YAML config to redirect people to the discussions for feedback and general questions, while handling bug reports and problems through issues. At least that's what I usually do for bigger projects. Although, like I've said, it's your call. 
![image](https://user-images.githubusercontent.com/62217720/187896178-21e611f3-bfd3-470b-ab48-263968b5a806.png)

**Comment by mattszymanko** [comment]
So, @relaxtakenotes, what do you think about implementing them? Something you'll think about, or totally off of the table?

**Comment by relaxtakenotes** [comment]
not really. our project is not of a scale that requires it

**Comment by mattszymanko** [comment]
Alright, no problem. Thanks for clearing that one out, appreciate it. And, of course, great work on your project.

Have a good one.

**Comment by relaxtakenotes** [comment]
yea np. thanks for the feedback and the suggestion
