### ISSUE TITLE
All sounds except explosions reverb and bullet cracks don't work (ALSO ANOTHER ZETA PLAYERS BUG)

### ISSUE THREAD

**Issue by HyperNeonX** [modusmogulus/GmodDynamicWeaponReverb#28]
As the title suggests, suddently all reverb sfx doesnt work except for explosions and bullet cracks.
Also before this bug, zeta players whenever they use their "other weapons" (such as tf2 weapons) this error shows up:

[Dynamic Weapon Reverb] lua/autorun/server/dwr_server.lua:129: attempt to index field 'Primary' (a nil value)
  1. v - lua/autorun/server/dwr_server.lua:129
   2. unknown - lua/includes/modules/hook.lua:96
    3. FireBullets - [C]:-1
     4. ShootWeapon - lua/zeta/weapon_handling.lua:324
      5. FireWeapon - lua/zeta/weapon_handling.lua:340
       6. unknown - lua/zeta/state_functions.lua:750
        7. unknown - lua/entities/npc_zetaplayer.lua:1509 (x2)
       
Their HL2 weapons work just fine, also I already reported this issue with the zeta's dev about this.

**Comment by relaxtakenotes** [comment]
cant replicate the first issue (i am playing right now, everything works just fine. check for conflicts i suppose)
for zeta players i can push a temp fix until the dev starts networking the weapon.primary field

**Comment by HyperNeonX** [comment]
Hmm i dont have anything that could conflict, im gonna try deactivating all addons and check

**Comment by HyperNeonX** [comment]
There's indeed a conflict, but im not sure which addon is it, could any sound replacement be causing trouble?

**Comment by relaxtakenotes** [comment]
usually sound replacements are just file replacements so they shouldn't cause trouble. if you can't find the conflict you can send me over your mod collection and i'll check myself

**Comment by HyperNeonX** [comment]
Ok, found the conflict, it was a suppression mod hah, the zeta's bug still persists, but still. thanks for the help

**Comment by relaxtakenotes** [comment]
it overrides entityfirebullets for no reason so no wonder... it's also an fps destroyer. i will push the fix and some additional changes a bit later

**Comment by relaxtakenotes** [comment]
pushed. check it out

**Comment by HyperNeonX** [comment]
Works perfectly, really great job
