### ISSUE TITLE
Realistic default value for the "speed of sound" Setting 

### ISSUE THREAD

**Issue by xray-tango** [modusmogulus/GmodDynamicWeaponReverb#29]
The value of 13430.00 Should match the Real Life speed of sound travelling through Air (343m/s) perfectly.

**Comment by relaxtakenotes** [comment]
sure. will change in the next update

**Comment by relaxtakenotes** [comment]
pushed to workshop

**Comment by xray-tango** [comment]
Alright, please undo this change, the latest commit seems to have also made it so that simply having 343 is enough to have the proper speed of sound so this change now makes it so that the sound has almost no travel time :/

**Comment by relaxtakenotes** [comment]
lol ok

**Comment by GoatyGoatster** [comment]
> The value of 13430.00 Should match the Real Life speed of sound travelling through Air (343m/s) perfectly.

Do you know the realistic values for sound occlusion and reflections? That'd be really nice; thank you if you do.
