### ISSUE TITLE
not compatible with '[VManip] Dynamic Kicking'

### ISSUE THREAD

**Issue by Sniper4721** [modusmogulus/GmodDynamicWeaponReverb#33]
pressing [bind] button to vmanip's kicking creates this addon's current equipped weapons sounds, 
https://www.youtube.com/watch?v=9lZgeb1jDME

**Comment by relaxtakenotes** [comment]
this mod is better: https://steamcommunity.com/sharedfiles/filedetails/?id=1987521428&searchtext=mighty+foot
i will look into this issue though.

**Comment by relaxtakenotes** [comment]
fixed in the dev branch. will be present in the next update.
