### ISSUE TITLE
an honestly good suggestion

### ISSUE THREAD

**Issue by GittyMuh** [modusmogulus/GmodDynamicWeaponReverb#34]
add a limit to how many reverb sounds can be played at once. and add a volume slider to the reverbs. when some guns on the tfa base fire really fast the shooting sound is drowned out by the obnoxiously loud reverbs. and Arc9 has issues with silencer detection for DWR and the reverbs are ear bleedingly annoying

**Comment by relaxtakenotes** [comment]
> 

what? there's a volume slider. if you cant find it then find the convar that starts with cl_dwr

**Comment by relaxtakenotes** [comment]
we also fix the shotgun issues by preventing reverb from initiating in the same tick.

**Comment by GittyMuh** [comment]
> we also fix the shotgun issues by preventing reverb from initiating in the same tick.

congrats. but fully auto weapons like vectors and mac11's. their high rpm. it would be a good thing to have a limit on how many reverb's can be active at once

**Comment by relaxtakenotes** [comment]
> > > 
> > 
> > 
> > what? there's a volume slider. if you cant find it then find the convar that starts with cl_dwr
> 
> i dont remember seeing one. might have been a recent update?

nope. was there since the dev version

**Comment by relaxtakenotes** [comment]
> > Author
> 
> so there wont be like 10 sounds a second overlapping with eachother causing fully auto weapons in open spaces to drown out the enemies sounds completely

turn down the volume bro

**Comment by GittyMuh** [comment]
> > > Author
> > 
> > 
> > so there wont be like 10 sounds a second overlapping with eachother causing fully auto weapons in open spaces to drown out the enemies sounds completely
> 
> turn down the volume bro

so youre telling me to make the volume 0.0001 just because youre too lazy to add a reverb limit so i can hear my miniguns shooting sounds instead of endless reverbs which drown out literally anything and get so loud it starts distorting it self.
NO THANK YOU!!!

**Comment by relaxtakenotes** [comment]
> > > > Author
> > > 
> > > 
> > > so there wont be like 10 sounds a second overlapping with eachother causing fully auto weapons in open spaces to drown out the enemies sounds completely
> > 
> > 
> > turn down the volume bro
> 
> so youre telling me to make the volume 0.0001 just because youre too lazy to add a reverb limit so i can hear my miniguns shooting sounds instead of endless reverbs which drown out literally anything and get so loud it starts distorting it self. NO THANK YOU!!!

ur just being an ass for no reason. fuck off

**Comment by GittyMuh** [comment]
but decreasing the volume also makes all guns reverbs silent
cause some guns shoot slower. or are semi auto

**Comment by GittyMuh** [comment]
youre a dumbass

**Comment by GittyMuh** [comment]
gl:hf

**Comment by RetardTroller** [comment]
@GittyMuh kill yourself

**Comment by GittyMuh** [comment]
yeah yeah. ignore the user and their valid suggestions on fixing weapons with very high rpm by adding reverb limits.

**Comment by GittyMuh** [comment]
> @GittyMuh kill yourself

uncalled for. manchild.

**Comment by relaxtakenotes** [comment]
> yeah yeah. ignore the user and their valid suggestions on fixing weapons with very high rpm by adding reverb limits.

ur the one that started calling me lazy after i worked my ass off on this mod for the whole summer. im sure the sound designers would love to hear you say that too

**Comment by RetardTroller** [comment]
> > @GittyMuh kill yourself
> 
> uncalled for. manchild.

retard = trolled by RETARDTROLLER (ME)

"why is gunfire so loud man wtf turn it down plz it hurts my SOY GOYIM EARS " ))))))

**Comment by GittyMuh** [comment]
> > > @GittyMuh kill yourself
> > 
> > 
> > uncalled for. manchild.
> 
> retard = trolled by RETARDTROLLER (ME)
> 
> "why is gunfire so loud man wtf turn it down plz it hurts my SOY GOYIM EARS " ))))))

just cause you named yourself retard troller doesnt make you less of a retard than a retard, retard.

**Comment by GittyMuh** [comment]
> > yeah yeah. ignore the user and their valid suggestions on fixing weapons with very high rpm by adding reverb limits.
> 
> ur the one that started calling me lazy after i worked my ass off on this mod for the whole summer. im sure the sound designers would love to hear you say that too

youre ignoring my point completely. i gave you a solid suggestion of a new feature which would fix the issue for semi auto guns reverbs also being quieter if you lower the volume so that fully auto guns wont be as loud

**Comment by RetardTroller** [comment]
> > > > @GittyMuh kill yourself
> > > 
> > > 
> > > uncalled for. manchild.
> > 
> > 
> > retard = trolled by RETARDTROLLER (ME)
> > "why is gunfire so loud man wtf turn it down plz it hurts my SOY GOYIM EARS " ))))))
> 
> just cause you named yourself retard troller doesnt make you less of a retard than a retard, retard.

sorry buddy old chum but it is YOU who doesn't know how to turn down their game volume hence i believe it is YOU who is the retard and it is YOU who has been trolled.

**Comment by relaxtakenotes** [comment]
> > > yeah yeah. ignore the user and their valid suggestions on fixing weapons with very high rpm by adding reverb limits.
> > 
> > 
> > ur the one that started calling me lazy after i worked my ass off on this mod for the whole summer. im sure the sound designers would love to hear you say that too
> 
> youre ignoring my point completely. i gave you a solid suggestion for a new feature which would fix the issue for semi auto guns reverbs also being quieter if you lower the volume so that fully auto guns wont be as loud

yeah goy go pester other mod devs idc

**Comment by Kotoshmet** [comment]
GittyMuh,
You're a such fucking annoying dick. Just disintegrate from this reality if you don't like something or can't talk to people in appropriate way.

**Comment by GittyMuh** [comment]
you both are dumber than fucking rocks

**Comment by GittyMuh** [comment]
> GittyMuh, You're a such fucking annoying dick. Just disintegrate from this reality if you don't like something or can't talk to people in appropriate way.

hey  i wasnt the one calling a whole gang on some guy who made a valid point

**Comment by relaxtakenotes** [comment]
> > GittyMuh, You're a such fucking annoying dick. Just disintegrate from this reality if you don't like something or can't talk to people in appropriate way.
> 
> hey i wasnt the one calling a whole gang on some guy who made a valid point

no we just have live notifs in discord

**Comment by GittyMuh** [comment]
> > sorry buddy old chum but it is YOU who doesn't know how to turn down their game volume hence i believe it is YOU who is the retard and it is YOU who has been trolled.
> 
> -turn down game volume -semi auto guns and silenced guns now have no sound -fully auto guns still cause reverbs to drown out all sound. bc all sound is now also silent

if youd open your fucking eyes. youd realize how fucking stupid all of you are. lower volume = everythings more silent. gun reverbs still drown out all sound

**Comment by GittyMuh** [comment]
> > > GittyMuh, You're a such fucking annoying dick. Just disintegrate from this reality if you don't like something or can't talk to people in appropriate way.
> > 
> > 
> > hey i wasnt the one calling a whole gang on some guy who made a valid point
> 
> no we just have live notifs in discord

so you run a discord full of ai

**Comment by GittyMuh** [comment]
> if youd open your fucking eyes. youd realize how fucking stupid all of you are. lower volume = everythings more silent. gun reverbs still drown out all sound

due to all sound being more silent

**Comment by relaxtakenotes** [comment]
> > > > GittyMuh, You're a such fucking annoying dick. Just disintegrate from this reality if you don't like something or can't talk to people in appropriate way.
> > > 
> > > 
> > > hey i wasnt the one calling a whole gang on some guy who made a valid point
> > 
> > 
> > no we just have live notifs in discord
> 
> so you run a discord full of ai

nope. devs that brought you this mod in the first place. as i said: fuck off goy and go pester others

**Comment by GittyMuh** [comment]
> nope. devs that brought you this mod in the first place. as i said: fuck off goy and go pester others

kinda immature of you to start calling me a jew for giving you a valid fucking suggestion of fixing high rpm guns

**Comment by relaxtakenotes** [comment]
> > nope. devs that brought you this mod in the first place. as i said: fuck off goy and go pester others
> 
> kinda immature of you to start calling me a jew for giving you a valid fucking suggestion of fixing high rpm guns

u dont even know the meaning of the word LOL

**Comment by GittyMuh** [comment]
> > > nope. devs that brought you this mod in the first place. as i said: fuck off goy and go pester others
> > 
> > 
> > kinda immature of you to start calling me a jew for giving you a valid fucking suggestion of fixing high rpm guns
> 
> u dont even know the meaning of the word LOL

youre stasrting to act like that one tf2 youtuber who called someone a reatrd and started spreading their npc bullshit on "I DID NOT MEAN IT IN THE WAY YOU THOUGHT IT WAS MEANT111!!!"

**Comment by GittyMuh** [comment]
yeah keep calling people jews. goyim

**Comment by GittyMuh** [comment]
you came from 4chan didnt you

**Comment by relaxtakenotes** [comment]
> > > > nope. devs that brought you this mod in the first place. as i said: fuck off goy and go pester others
> > > 
> > > 
> > > kinda immature of you to start calling me a jew for giving you a valid fucking suggestion of fixing high rpm guns
> > 
> > 
> > u dont even know the meaning of the word LOL
> 
> youre stasrting to act like that one tf2 youtuber who called someone a reatrd and started spreading their npc bullshit on "I DID NOT MEAN IT IN THE WAY YOU THOUGHT IT WAS MEANT111!!!"

nah mate u cant gaslight me like that. bring up the definitions of these words and you'll see

**Comment by Kotoshmet** [comment]
GittyMuh, just fuck off. Seriously, touch some goddamn grass. Your toxicity is over the top. You're covering the developers with curse words. If you really wanted to help us, then you would talk with us in a more friendly way. And stop spamming, you look ridiculous.

**Comment by GittyMuh** [comment]
> GittyMuh, just fuck off. Seriously, touch some goddamn grass. Your toxicity is over the top. You're covering the developers with curse words. If you really wanted to help us, then you would talk with us in a more friendly way. And stop spamming, you look ridiculous.

says the word "lazy" once
-whole gang of dogs suddenly calling me a retard
im toxic? youre gaslighting ME

**Comment by RetardTroller** [comment]
> 

um buddy. goyim means "non jewish"

**Comment by relaxtakenotes** [comment]
> > GittyMuh, just fuck off. Seriously, touch some goddamn grass. Your toxicity is over the top. You're covering the developers with curse words. If you really wanted to help us, then you would talk with us in a more friendly way. And stop spamming, you look ridiculous.
> 
> says the word "lazy" once -whole gang of dogs suddenly calling me a retard im toxic? youre gaslighting ME

you come here demanding shit from a guy that you dont even know and havent even paid in any way, then you call him lazy. do you think that's acceptable?

**Comment by GittyMuh** [comment]
> > 
> 
> um buddy. goyim means "non jewish"

im slowly starting to think im speaking to "/b/ros" all over again
jesus fucking christ the more i know. dont even suggest anything to garrysmod addon creators cause theyll either completely ignore you or gaslight you calling you toxic for saying something even remotely mean

**Comment by relaxtakenotes** [comment]
> > > 
> > 
> > 
> > um buddy. goyim means "non jewish"
> 
> im slowly starting to think im speaking to "/b/ros" all over again jesus fucking christ the more i know. dont even suggest anything to garrysmod addon creators cause theyll either completely ignore you or gaslight you calling you toxic for saying something even remotely mean

yeah bro dont say mean shit to people that did a mod for free for you to use. it's really simple LOL

**Comment by Kotoshmet** [comment]
> > GittyMuh, just fuck off. Seriously, touch some goddamn grass. Your toxicity is over the top. You're covering the developers with curse words. If you really wanted to help us, then you would talk with us in a more friendly way. And stop spamming, you look ridiculous.
> 
> says the word "lazy" once -whole gang of dogs suddenly calling me a retard im toxic? youre gaslighting ME

Your grammar is fucking horrible. Read some books, kid.
If we were gaslighting you we would just fucking ignore you because you're acting like a typical school boy from 3rd grade.

**Comment by GittyMuh** [comment]
> > > GittyMuh, just fuck off. Seriously, touch some goddamn grass. Your toxicity is over the top. You're covering the developers with curse words. If you really wanted to help us, then you would talk with us in a more friendly way. And stop spamming, you look ridiculous.
> > 
> > 
> > says the word "lazy" once -whole gang of dogs suddenly calling me a retard im toxic? youre gaslighting ME
> 
> you come here demanding shit from a guy that you dont even know and havent even paid in any way, then you call him lazy. do you think that's acceptable?

-"havent payd in any way"
the jew calling me a jew.
kinda jewish innit.

https://gfycat.com/warlikeaffectionateantarcticfurseal-money-cash-vince-mcmahon-superstars
^ gmod addon creators when they open a suggestions channel

**Comment by relaxtakenotes** [comment]
> > > > GittyMuh, just fuck off. Seriously, touch some goddamn grass. Your toxicity is over the top. You're covering the developers with curse words. If you really wanted to help us, then you would talk with us in a more friendly way. And stop spamming, you look ridiculous.
> > > 
> > > 
> > > says the word "lazy" once -whole gang of dogs suddenly calling me a retard im toxic? youre gaslighting ME
> > 
> > 
> > you come here demanding shit from a guy that you dont even know and havent even paid in any way, then you call him lazy. do you think that's acceptable?
> 
> -"havent payd in any way" the jew calling me a jew. kinda jewish innit.
> 
> https://gfycat.com/warlikeaffectionateantarcticfurseal-money-cash-vince-mcmahon-superstars ^ gmod addon creators when they open a suggestions channel

i havent ever demanded money from no one, i only demand respect. you failed to deliver thus fuck off

**Comment by relaxtakenotes** [comment]
you're still failing to realize the meaning of "goy". let me help you:
Goy - a term used by a Jew to refer to someone who is not Jewish
Jew - a member of the people and cultural community whose traditional religion is Judaism and who trace their origins through the ancient Hebrew people of Israel to Abraham.
Guess what, none of them are even slurs or insults. So shut the fuck up

**Comment by GittyMuh** [comment]
> > > > > GittyMuh, just fuck off. Seriously, touch some goddamn grass. Your toxicity is over the top. You're covering the developers with curse words. If you really wanted to help us, then you would talk with us in a more friendly way. And stop spamming, you look ridiculous.
> > > > 
> > > > 
> > > > says the word "lazy" once -whole gang of dogs suddenly calling me a retard im toxic? youre gaslighting ME
> > > 
> > > 
> > > you come here demanding shit from a guy that you dont even know and havent even paid in any way, then you call him lazy. do you think that's acceptable?
> > 
> > 
> > -"havent payd in any way" the jew calling me a jew. kinda jewish innit.
> > https://gfycat.com/warlikeaffectionateantarcticfurseal-money-cash-vince-mcmahon-superstars ^ gmod addon creators when they open a suggestions channel
> 
> i havent ever demanded money from no one, i only demand respect. you failed to deliver thus fuck off

what. you expect me to resepct your stupid decision on ignoring something as easy as adding a limiter on how many times an audio can be played within a set amount of time
just to fix guns with a very high rate of fire
ofc id try to talk you out of your stupidity and/or get a REAL reason why you wont add such a simple yet useful thing

**Comment by GittyMuh** [comment]
and im supposed to act like your dog?

**Comment by GittyMuh** [comment]
if you were really annoyed by me youd have fucked off

**Comment by Kotoshmet** [comment]
> and im supposed to act like your dog?

Why your mom allowed you to use the computer? Stop posting cringe.

**Comment by GittyMuh** [comment]
imma sit here as long as you have energy to keep spreading your retardation

**Comment by Kotoshmet** [comment]
> imma sit here as long as you have energy to keep spreading your retardation

🤡🤡🤡🤡🤡🤡

**Comment by relaxtakenotes** [comment]
then come to our discord bro lets see how long you'll hold up

**Comment by GittyMuh** [comment]
> > imma sit here as long as you have energy to keep spreading your retardation
> 
> clown_faceclown_faceclown_faceclown_faceclown_faceclown_face

clown emojis arent valid arguments

**Comment by GittyMuh** [comment]
> then come to our discord bro lets see how long you'll hold up

"""mic up"""

**Comment by Kotoshmet** [comment]
> > > imma sit here as long as you have energy to keep spreading your retardation
> > 
> > 
> > clown_faceclown_faceclown_faceclown_faceclown_faceclown_face
> 
> clown emojis arent valid arguments

Your curses are not valid arguments too though.

**Comment by relaxtakenotes** [comment]
dodging?

**Comment by RetardTroller** [comment]
> > > 
> > 
> > 
> > um buddy. goyim means "non jewish"
> 
> im slowly starting to think im speaking to "/b/ros" all over again jesus fucking christ the more i know. dont even suggest anything to garrysmod addon creators cause theyll either completely ignore you or gaslight you calling you toxic for saying something even remotely mean

goy
/ɡɔɪ/
nounDEROGATORY•INFORMAL
plural noun: goyim
a Jewish name for a non-Jewish person.

I win.

**Comment by relaxtakenotes** [comment]
ok gaslighter just lmk when u wanna go on discord and stop dodging

**Comment by Kotoshmet** [comment]
> > > > > imma sit here as long as you have energy to keep spreading your retardation
> > > > 
> > > > 
> > > > clown_faceclown_faceclown_faceclown_faceclown_faceclown_face
> > > 
> > > 
> > > clown emojis arent valid arguments
> > 
> > 
> > Your curses are not valid arguments too though.
> 
> neither are yours. retard"troller"

Then come to our discord server so we can talk with you, if you're so brave.

**Comment by RetardTroller** [comment]
> > > > > imma sit here as long as you have energy to keep spreading your retardation
> > > > 
> > > > 
> > > > clown_faceclown_faceclown_faceclown_faceclown_faceclown_face
> > > 
> > > 
> > > clown emojis arent valid arguments
> > 
> > 
> > Your curses are not valid arguments too though.
> 
> neither are yours. retard"troller"

i think you responded to the wrong person buddy. I did not type any of those words that you quoted. I think this is evidence enough that I, as the troller of retards, have successfully identified YOU as a retard of whom i am destined to troll

**Comment by GittyMuh** [comment]
> ok gaslighter just lmk when u wanna go on discord and stop dodging

dodging???
YOURE _**DODGING**_ an easy fix to your already good addon that would make it even better. and even more friendly to guns with a higher rpm.

**Comment by GittyMuh** [comment]
if youd add the fucking limiter to how many times reverbs can be played within a second it would fix the earape issue. your addon will die like the previous one. but instead of shotguns killing it off. youll have to put (DO NOT USE GUNS WITH AN RPM HIGHER OF 750 WITH THIS ADDON!!!)

**Comment by RetardTroller** [comment]
> > ok gaslighter just lmk when u wanna go on discord and stop dodging
> 
> dodging??? YOURE _**DODGING**_ an easy fix to your already good addon that would make it even better. and even more friendly to guns with a higher rpm.

ur litterally saying "wtf pls make this mod designed for realism able to be made unrealistic" ur just coping cuz you could never make a mod that goes right to the front page of the workshop.

**Comment by relaxtakenotes** [comment]
again lmk when u wanna go on discord and settle this i dont wanna talk to you in here

**Comment by RetardTroller** [comment]
> > > > ok gaslighter just lmk when u wanna go on discord and stop dodging
> > > 
> > > 
> > > dodging??? YOURE _**DODGING**_ an easy fix to your already good addon that would make it even better. and even more friendly to guns with a higher rpm.
> > 
> > 
> > ur litterally saying "wtf pls make this mod designed for realism able to be made unrealistic" ur just coping cuz you could never make a mod that goes right to the front page of the workshop.
> 
> -designed for realism -using that as an excuse to not add further options for players who want to use this addon but in a more personalized way tl:dr youre all fucking children

Im a child?? how come my ears can handle noise in a video game and yours can't?
