### ISSUE TITLE
one last message to you stubborn fucks

### ISSUE THREAD

**Issue by GittyMuh** [modusmogulus/GmodDynamicWeaponReverb#35]
>addon is made for realism
>refuses to add a very useful option to fix high rpm weapons bc of "muh reelizm"
>ignores the fact that people can still keep it realistic. the addon will still be realistic. but ontop of that it will also be a lot more customization options and would also have a lot more options to edit it in a way so that everyone/anyone can use it in any way they want.

tl:dr what makes an addon good is being able to edit it to your liking. turning something great into something better to enjoy it more.
for people who love fully auto high rpm guns. an audio limiter would be the perfect fix.

 ill watch the day your addon hits the shitter the same way the other one did. mr "worked my ass off"

**Comment by Kotoshmet** [comment]
Fuck you too, brainless maggot.

**Comment by GittyMuh** [comment]
*slow clap*

**Comment by GittyMuh** [comment]
there you go. the only victory youll ever have

**Comment by GittyMuh** [comment]
now go flex it

**Comment by relaxtakenotes** [comment]
ok little man i'll go get a high paying job meanwhile u can sit here and work a minimal wage job
