### ISSUE TITLE
>starts calling me a fag

### ISSUE THREAD

**Issue by GittyMuh** [modusmogulus/GmodDynamicWeaponReverb#36]
since when did gay people become the reason youre a dumbass who ignores suggestions just cause of "muh reelizm"
"spam"
even then you and your little dog "retard troller"
are stupid enough to keep responding. if you were truely mad at me youd be closing these issues without even responding. did you forget the term. "DONT FEED THE TROLLS"
i didnt even try to troll you. thats the art of true trolling """retard troller"""

so long my friends. ill see you when you finally crack open that thick shell around you. 

![cy](https://user-images.githubusercontent.com/79758136/188456565-cf913033-0229-42d3-bce5-68ddc37ca888.png)

**Comment by relaxtakenotes** [comment]
ok bro cry more
