### ISSUE TITLE
Request: Support for ARC-9 Base? (physical bullets)

### ISSUE THREAD

**Issue by HyperNeonX** [modusmogulus/GmodDynamicWeaponReverb#37]
So enabling ballistics in this base, weapons always create the reverb whenever the bullet hits, making an delayed result. Disabling this, weapons works just fine, heres the github link to the base just in case : https://github.com/HaodongMo/ARC-9

**Comment by relaxtakenotes** [comment]
wtf another weapon base by arctic... ok i'll look into it

**Comment by HyperNeonX** [comment]
Yea, there are multiple right now, but heres the standard ones : https://github.com/HaodongMo/ARC-9-Standard-Weapons

**Comment by relaxtakenotes** [comment]
aight cheers i'll look into it whenever im free. keep in mind that it seems the weapon base is in heavy development so whatever i do to detect phys bullets might become invalid in the next updates

**Comment by relaxtakenotes** [comment]
added in the dev branch. will be in the next update
