### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by relaxtakenotes** [modusmogulus/GmodDynamicWeaponReverb#41]
~~1) make hooks for detecting phys bullets hook only if the respective weapon packs are mounted~~
2) actually HOOK arc9 sendbullet (rn it just completely replaces the og function with a 1:1 copy except dwr stuff)

**Comment by HyperNeonX** [comment]
I know im not supposed to ask here but, i still dont understand the sound occlusion rays and reflections per sound occlusion ray settings, its better to have them on the highest or lowest values? what are they for?

**Comment by relaxtakenotes** [comment]
> I know im not supposed to ask here but, i still dont understand the sound occlusion rays and reflections per sound occlusion ray settings, its better to have them on the highest or lowest values? what are they for?

there's nothing for me to explain if you didn't get my previous explanation. just keep it at the default values and don't worry about it

**Comment by ZarikoMarcer** [comment]
It would be really nice if the reverb were based on weapon sounds instead of ammo types.

**Comment by relaxtakenotes** [comment]
> It would be really nice if the reverb were based on weapon sounds instead of ammo types.

hint me at a way to do it without complicated audio analysis and doing c++ modules

**Comment by justkingdion** [comment]
Personally I would like to have some compatibility with the ArcCW Gunsmith Offensive (GSO) items. This has an entire set of attachment entities including suppressors and subsonic ammo, which then apply their own sound reduction percentage as a perk. Despite having a suppressor on, every weapon will still produce full reverb.

**Comment by relaxtakenotes** [comment]
finally did the point 2
