### ISSUE TITLE
Unique bullet Impacts and ricocshet Sounds for weapon with phys bullets (Like the unpatched ARC9 bullets but intended)

### ISSUE THREAD

**Issue by xray-tango** [modusmogulus/GmodDynamicWeaponReverb#42]
When I tried this addon with the unpatched ARC9 base I really liked how you could hear the bullet impacting/ricocheting off of things some time after seeing it happen depending on how far away it was. It really pronounced how good the travelling sound system is.
It was really satisfying when you had a gun that's bullet travelled at 360m/s and you shot at something 350 meters away you heard the bullet impact almost 2 seconds after the shot was fired or 1 second after it impacted.
 With this being fixed shooting weapons are not as satisfying as it used to be with the unpatched version. And that's also true for mid to close range as well, on those ranges you could have still heard the bullet impacting 0.1 sec after being shot.

Having a dedicated bullet impact and ricocshet sounds for phys bullets would add a lot to the emersion of this addon even if it's not necessarily 100% realistic in all situations   

P.S.: Having different kind of impact sounds, loudness, strength, range and reverb modifiers for different materials would add a crap ton to this addon
For example hitting a metal target at a long range would still give out a loud metallic impact sound when the sound of it reaches you, while the impact on a soft target like sand or dirt could not or just barely be heard from far away but could be heard on close to mid range.

**Comment by relaxtakenotes** [comment]
Beyond the scope of this mod. We can only provide realistic reverb, not bullet impacts or ricochet.
