### ISSUE TITLE
Explosion Bug

### ISSUE THREAD

**Issue by Joelasmama** [modusmogulus/GmodDynamicWeaponReverb#43]
Everytime I fire a grenade or rocket launcher it shows up this 
![image](https://user-images.githubusercontent.com/113927556/191064377-f9da9505-3807-4908-b115-8912aca0395e.png)

![image](https://user-images.githubusercontent.com/113927556/191064443-5dfe63ad-0742-4b49-9d7f-f75c0937cac8.png)

**Comment by relaxtakenotes** [comment]
fixed

**Comment by Joelasmama** [comment]
> fixed

do i have to wait till the addon updates?

**Comment by relaxtakenotes** [comment]
> > fixed
> 
> do i have to wait till the addon updates?

pushed to workshop already

**Comment by Joelasmama** [comment]
> > > fixed
> > 
> > 
> > do i have to wait till the addon updates?
> 
> pushed to workshop already

Ah nice, cheers (Patience is key)
