### ISSUE TITLE
MW Marksman sweps creates reverb only when bullet hits/Weapon sounds way louder than the reverb?

### ISSUE THREAD

**Issue by HyperNeonX** [modusmogulus/GmodDynamicWeaponReverb#44]
So recently the MW Marksman rifles got released, and I found that every shot that hits the wall creates the reverb, while all other MW related sweps works fine, heres a clip of that :

https://user-images.githubusercontent.com/112649739/191699966-bc9f5d5b-97f1-4d1d-9012-94ca94af67ef.mp4

Also I dont know if im wrong but, the weapon sounds seem to sound way louder than the reverb?, It sounds odd at mid (and sometimes long) ranges especially whenever the muffled effect gets aplied to the reverb (Also the reverb volume is 100, and the only way I could find a remedy for this is using the Dynamic Sound addon which is kinda old and buggy sadly)
Heres a clip:

https://user-images.githubusercontent.com/112649739/191700974-63ff2a63-87e3-4137-957a-a3e9d8e63c2f.mp4

**Comment by relaxtakenotes** [comment]
1) Hm, thought something was weird but didn't really notice it. I'll look into it
2) Yeah because weapon sounds aren't processed by default, you need to enable sv_dwr_network_sounds for it

**Comment by HyperNeonX** [comment]
Thank you! Keep up the good work

**Comment by relaxtakenotes** [comment]
Pushed the fixes to workshop. Additionally fixed the silencer detection for mw2019 sweps
