### ISSUE TITLE
 error with MW crossbows when you dont use the default arrow modification

### ISSUE THREAD

**Issue by ujel-ragewars** [modusmogulus/GmodDynamicWeaponReverb#46]
[Dynamic Weapon Reverb] lua/autorun/server/dwr_server.lua:20: attempt to call method 'GetAllAttachmentsInUse' (a nil value)
  1. getSuppressed - lua/autorun/server/dwr_server.lua:20
   2. v - lua/autorun/server/dwr_server.lua:230
    3. unknown - lua/includes/modules/hook.lua:96
     4. FireBullets - [C]:-1
      5. Impact - lua/entities/mg_arrow/init.lua:150
       6. Impact - lua/entities/mg_arrow_emp/init.lua:40
        7. unknown - lua/entities/mg_arrow/init.lua:91 (x2)

https://user-images.githubusercontent.com/114201722/192118906-238b2db2-25ff-423b-90c8-f206c5bd4795.mp4

**Comment by relaxtakenotes** [comment]
Will be fixed next workshop update
