### ISSUE TITLE
Lua error and reverb isnt heard

### ISSUE THREAD

**Issue by Drogo-man** [modusmogulus/GmodDynamicWeaponReverb#47]
[Dynamic Weapon Reverb] lua/autorun/client/dwr_client.lua:448: attempt to index upvalue 'blacklist' (a nil value)
    1. func - lua/autorun/client/dwr_client.lua:448
        2. unknown - lua/includes/extensions/net.lua:33

**Comment by relaxtakenotes** [comment]
Fixed. Will be pushed to workshop shortly
