### ISSUE TITLE
bug with explosions in the latest update

### ISSUE THREAD

**Issue by ujel-ragewars** [modusmogulus/GmodDynamicWeaponReverb#48]
[Dynamic Weapon Reverb] lua/autorun/client/dwr_client.lua:258: attempt to index local 'weapon' (a nil value)
  1. playReverb - lua/autorun/client/dwr_client.lua:258
   2. explosionProcess - lua/autorun/client/dwr_client.lua:517
    3. v - lua/autorun/client/dwr_client.lua:522
     4. unknown - lua/includes/modules/hook.lua:96 

https://user-images.githubusercontent.com/114201722/192163561-36c2e7b6-a0d8-413b-884a-5e5f754998d4.mp4

**Comment by relaxtakenotes** [comment]
Fixed. Will push to the workshop shortly
