### ISSUE TITLE
Addon error popping up

### ISSUE THREAD

**Issue by Paradoxidus** [modusmogulus/GmodDynamicWeaponReverb#49]
Good day! I would like to report an issue where I occasionally get this:

[Dynamic Weapon Reverb] lua/autorun/client/dwr_client.lua:449: attempt to call method 'GetActiveWeapon' (a nil value)
  1. func - lua/autorun/client/dwr_client.lua:449
   2. unknown - lua/includes/extensions/net.lua:33 (x2)

I keep getting this usually whenever Combine NPCs usually shoot. My guess is probably the custom weapons that these NPCs use, but may you check if this is an issue regarding that too? Thank you!

**Comment by relaxtakenotes** [comment]
Love accounting for other peoples mistakes, that totally doesn't bloat our mod... Anyway, try the newest workshop update, should fix it.

**Comment by Paradoxidus** [comment]
Thank you! I appreciate this.
