### ISSUE TITLE
Weapon blacklisting

### ISSUE THREAD

**Issue by SnoopDash** [modusmogulus/GmodDynamicWeaponReverb#50]
Hey, can the Weapon blacklisting can be on server side and not client side ?

In my Metro 2033 project we use TFA Bow, Crossbow and i would like to know if use the command 'cl_dwr_blacklist_add' with my current weapon i wanted to blacklist. The reverb sound will be delete for everyone who us Bow as weapon ?

Thanks for your time, and have a nice day

SnoopDash

**Comment by relaxtakenotes** [comment]
I can make a separate command so that you can block weapons by their class serverside. Currently it's clientside only.

**Comment by SnoopDash** [comment]
Okay, perfect i will wait to add your work on my project when this command will be there. Nice work by the way keep going guys you rock !

**Comment by relaxtakenotes** [comment]
All the calculations will be done clientside still, the server just networks its own blacklist whenever it changes and the client can still override it until it gets networked again (on player respawn). Will that do for ya?

**Comment by SnoopDash** [comment]
Yes, i will be perfect !

**Comment by relaxtakenotes** [comment]
nvm lol i have to stop overengineering shit i found a simpler solution that allows it to be not overriden by clients so yea once i test it out i'll push it to public

**Comment by relaxtakenotes** [comment]
try out the newest commit

**Comment by SnoopDash** [comment]
] sv_dwr_blacklist_add
Missing weapon class.

**Comment by relaxtakenotes** [comment]
yea you need to specify a weapon class, you can either get it by copying it from the spawn menu where u get it from or by using cl_dwr_weaponclass

**Comment by SnoopDash** [comment]
] sv_dwr_blacklist_add rust_crossbow
Added rust_crossbow to the blacklist.

It's working !

**Comment by relaxtakenotes** [comment]
alrighty, enjoy. gonna push it to workshop rn
