### ISSUE TITLE
MWB Shotguns has delay using slug ammo/ARC-9 Shotguns sound extremely loud

### ISSUE THREAD

**Issue by HyperNeonX** [modusmogulus/GmodDynamicWeaponReverb#51]
Not while ago MWB got an update, and it seems like it broke something with dwr, It only occurs with slug ammo as far im aware :

https://user-images.githubusercontent.com/112649739/195456312-82dc8b3f-94d7-4ab8-a71c-7bf054466fe5.mp4

And arc 9 shotguns are really loud, I assume this is due to every bullet counts as a reverb or something like that (And Im aware that arc 9 is wip and that I can blacklist weapons, but im just reporting this :))

https://user-images.githubusercontent.com/112649739/195456487-a0d77dc1-7700-4154-9b05-5f60def5ca2f.mp4

volume warning lol

**Comment by relaxtakenotes** [comment]
I'll look into these as soon as possible. School's hitting hard. But as for the Arc9 shotgun earrape I thought it was fixed because of a certain check I do but I guess in Arc9 it acts differently. MWB probably just applied the same sniper rifle physics to the slug

**Comment by HyperNeonX** [comment]
Kinda late but also, theres a bug with the suppressors with the arc 9 weapons, they don't get any reverb effect

**Comment by HyperNeonX** [comment]
You could be really far away and the suppressed shot sound will still be heard

**Comment by relaxtakenotes** [comment]
Can you link the BO2 weapon pack?

**Comment by relaxtakenotes** [comment]
fixed
