### ISSUE TITLE
This addon breaks certain weapons that has looping sfx

### ISSUE THREAD

**Issue by HyperNeonX** [modusmogulus/GmodDynamicWeaponReverb#52]
So I stumble upon an issue with weapons that happens with weapons that include some sort of loop sfx in it, heres what I mean:

https://user-images.githubusercontent.com/112649739/200979290-6105d6f1-e5a5-4e5d-9047-0727d27ee71e.mp4

the only way that I could solve this is by either disabling/deleting the addon or changing sv_dwr_network_sounds to 0 (Which i dont want to change lol) not even blacklisting or anything else fixes this.
Hope you can solve this :)

**Comment by relaxtakenotes** [comment]
Couldn't fix it, that's why it was an option. Wish there was a solution but I can't think of one. Not that I will because I'm not maintaining this mod anymore.
