### ISSUE TITLE
New update seems to break ARC9's recoil completely

### ISSUE THREAD

**Issue by HyperNeonX** [modusmogulus/GmodDynamicWeaponReverb#53]
Whenever I use this addon, all ARC9 recoil becomes completely non-existent, deleting this fixes the issue, this are the errors that pops up:

[arc-9-main] lua/autorun/server/dwr_server.lua:113: attempt to index global 'entity' (a nil value)
  1. SendBullet - lua/autorun/server/dwr_server.lua:113
   2. ShootPhysBullet - addons/arc-9-main/lua/arc9/shared/sh_physbullet.lua:147
    3. DoProjectileAttack - addons/arc-9-main/lua/weapons/arc9_base/sh_shoot.lua:465
     4. DoPrimaryAttack - addons/arc-9-main/lua/weapons/arc9_base/sh_shoot.lua:376
      5. unknown - addons/arc-9-main/lua/weapons/arc9_base/sh_shoot.lua:228
      
[arc-9-main] lua/autorun/server/dwr_server.lua:113: attempt to index global 'entity' (a nil value)
  1. SendBullet - lua/autorun/server/dwr_server.lua:113
   2. ShootPhysBullet - addons/arc-9-main/lua/arc9/shared/sh_physbullet.lua:147
    3. Penetrate - addons/arc-9-main/lua/weapons/arc9_base/sh_penetration.lua:186
     4. AfterShotFunction - addons/arc-9-main/lua/weapons/arc9_base/sh_shoot.lua:636
      5. callback - addons/arc-9-main/lua/arc9/shared/sh_physbullet.lua:424
       6. unknown - lua/autorun/server/zippy_realistic_blood.lua:50
        7. FireBullets - [C]:-1
         8. ProgressPhysBullet - addons/arc-9-main/lua/arc9/shared/sh_physbullet.lua:413
          9. v - addons/arc-9-main/lua/arc9/shared/sh_physbullet.lua:239
           10. unknown - lua/includes/modules/hook.lua:96

It mentions "zippy_realistic_blood.lua:50" but that doesnt intervene with the addon. Also in the arc9 discord, the dev mentions that arc 9 is very soon to release, I wanna mention this just in case any changes comes up

**Comment by relaxtakenotes** [comment]
I don't get these errors, however I don't get any recoil either even after removing the code responsible for hooking into arc9. Can you send me the weapon pack you're using?

**Comment by relaxtakenotes** [comment]
Actually nvm I get recoil with the csgo pack but it's very weird and laggy...

**Comment by relaxtakenotes** [comment]
will push a fix soon

**Comment by relaxtakenotes** [comment]
pushed
