### ISSUE TITLE
Lua error message when shooting from weapon, im using ARCCW

### ISSUE THREAD

**Issue by RedyRT** [modusmogulus/GmodDynamicWeaponReverb#54]
[Dynamic Weapon Reverb] lua/autorun/server/dwr_server.lua:207: attempt to index global 'entity' (a nil value)
    1. v - lua/autorun/server/dwr_server.lua:207
        2. unknown - lua/includes/modules/hook.lua:96

NOTE: In previous update there was no errors when shooting from these weapons like ARCCW

**Comment by relaxtakenotes** [comment]
will push a fix soon

**Comment by relaxtakenotes** [comment]
pushed

**Comment by RedyRT** [comment]
> pushed

thx
