### ISSUE TITLE
Sound doesnt play on non physical bullet weapons

### ISSUE THREAD

**Issue by juanito45dotcom** [modusmogulus/GmodDynamicWeaponReverb#56]
having an issues with reverb sound not playing on default HL2 weapons or any weapons that doesnt use physical bullets

**Comment by relaxtakenotes** [comment]
Sounds like something is overriding entityfirebullet! Look for a mod that changes the way bullets behave and try to disable it to see if that helps. That's the only way to fix it sadly because of the way hooks work in this game.

**Comment by relaxtakenotes** [comment]
You're the only one with this problem. It's a conflict of mods for sure

**Comment by juanito45dotcom** [comment]
lemme try to unsubcribe to all of the addons see if it work

**Comment by juanito45dotcom** [comment]
wait does this work with "Suppression (revisioned)" addons?

**Comment by juanito45dotcom** [comment]
ok that was the incompaltible addons

**Comment by relaxtakenotes** [comment]
Yeah the mod is poorly written and also destroys your FPS, I recommend not using it

**Comment by relaxtakenotes** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2920824143
Here's the improved version of that mod if you're interested.

**Comment by juanito45dotcom** [comment]
Zamn nice, also hey is it possible if ye can make the reverb mod work for other Valve titles?

**Comment by relaxtakenotes** [comment]
It's possible but we do not plan on making it a reality... just yet, maybe.

**Comment by juanito45dotcom** [comment]
good to know
