### ISSUE TITLE
No sound on any arccw, mwbase and etc guns

### ISSUE THREAD

**Issue by Ribauzinho** [modusmogulus/GmodDynamicWeaponReverb#57]
I was clearing some add-ons and i remove dwr3 accidentally and when i get in a game, the arccw, mwbase and etc guns don´t have sounds, just the sounds the bullets hit in the floor

idk what to do

https://user-images.githubusercontent.com/123598617/214706820-9d63b565-72d6-40a9-91aa-6637cdd67677.mp4

**Comment by relaxtakenotes** [comment]
restart the game...

**Comment by Ribauzinho** [comment]
> restart the game...

I'm not that dumb, i already restart, reinstall, restart my pc but nothing works

The fact removing dwr3 removed all my guns sounds from any weapon bases

**Comment by relaxtakenotes** [comment]
this cant happen sorry bro

**Comment by Ribauzinho** [comment]
> this cant happen sorry bro

Then gg´s, ty in the same way

**Comment by WEEZOOKARP** [comment]
there is properly no way for this to happen lmao

**Comment by WEEZOOKARP** [comment]
must have been one of your other addons

**Comment by relaxtakenotes** [comment]
invalid
