### ISSUE TITLE
Error while loading add-on

### ISSUE THREAD

**Issue by nsherbina1999** [modusmogulus/GmodDynamicWeaponReverb#58]
Appears at loading some map.

[Dynamic Weapon Reverb] lua/includes/extensions/table.lua:158: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Count - lua/includes/extensions/table.lua:158
    3. v - lua/autorun/server/dwr_server.lua:194
     4. unknown - lua/includes/modules/hook.lua:96 (x6319)

**Comment by nsherbina1999** [comment]
Also, I've disabled ARC9, and error disappeared.

**Comment by nsherbina1999** [comment]
My bad, it needs to be installed after Arc9.

**Comment by relaxtakenotes** [comment]
solved
