### ISSUE TITLE
Incompatibility with certain addons

### ISSUE THREAD

**Issue by PumaDeLuma** [modusmogulus/GmodDynamicWeaponReverb#61]
Hey, after testing with various addons, Dynamic Weapon Reverb does not make any sounds to weapons when the following addons are installed:

- RagShoot
- Global NPC Hearing System
- Realistic NPC Tracking and Aiming "Hitscan Dodging"
- Realistic Combine Soldier AI | FEAR-like AI
Just reporting it here since these addons  have nothing to do with weapon sounds but are somehow blocking the weapon reverb sounds to play.

**Comment by relaxtakenotes** [comment]
They override entityfirebullets, which we use to detect most gun shots.

**Comment by JaxOrSmthng** [comment]
Global NPC Hearing System and Realistic Combine Soldier AI | FEAR-like AI work fine for me (well, kinda. sometimes it doesnt output the correct sfx but its normal since its completely dynamic)
is it only sometimes or always

**Comment by PumaDeLuma** [comment]
> Global NPC Hearing System and Realistic Combine Soldier AI | FEAR-like AI work fine for me (well, kinda. sometimes it doesnt output the correct sfx but its normal since its completely dynamic) is it only sometimes or always

Always. Double tested it multiple times.

**Comment by JaxOrSmthng** [comment]
it works fine for me. are you sure you tested it correctly?

**Comment by PumaDeLuma** [comment]
I have. Just re-tested it but for some odd reason it works when DWR is enabled with the addons. It works but it sometimes doesn't like I have to unsubscribe, then subscribe again for the addons to work without issue.
