### ISSUE TITLE
Supressors dont work on ARC9 base

### ISSUE THREAD

**Issue by HyperNeonX** [modusmogulus/GmodDynamicWeaponReverb#62]
As the title says, none of the supressed weapons are working on ARC9 the reverb is always loud as if im not using any supressor, In ARCCW these ones actually work and does suppress the audio including th reverb

**Comment by relaxtakenotes** [comment]
yea cause i haven't added support for it yet. will do later maybe

**Comment by HyperNeonX** [comment]
Ohh got it, I thought it was a bug or something

**Comment by relaxtakenotes** [comment]
added
