### ISSUE TITLE
Sounds play on impact of bullet not on shot

### ISSUE THREAD

**Issue by CrafterRa** [modusmogulus/GmodDynamicWeaponReverb#65]
Hello ive noticed when playing with guns that have physical bullets that this addon sadly only works correctly with guns that have a raycast system meaning the bullet instanly hits where you shot. of you use this with a weapon with slow bullets like physical bullets the sound will play late because it only plays when the bullet hits. could you please implement this on shot not on bullet hit

**Comment by CrafterRa** [comment]
sorry cant make i video file limit to small but you can tried it yourself i used max payne weapons but also had this problom with arc9 tfa and other weapon bases

**Comment by CrafterRa** [comment]
so did it get implemented now or wasnt it possible?

**Comment by relaxtakenotes** [comment]
no ur just completely wrong

**Comment by CrafterRa** [comment]
how im i wrong i tested it with tfa and i still heared that the reverb was only played after the physical bullet hits instead when the weapon is fired. is it just not possible or is it a problem with the gun bases?

**Comment by CrafterRa** [comment]
im also not trying to annoy you with this but it just broke immersion a bit

**Comment by CrafterRa** [comment]
right now i want to test some addons and look with which it happens

**Comment by relaxtakenotes** [comment]
> how im i wrong i tested it with tfa and i still heared that the reverb was only played after the physical bullet hits instead when the weapon is fired. is it just not possible or is it a problem with the gun bases?
because it works

**Comment by CrafterRa** [comment]
is it supposed to be on bullet hit?

**Comment by relaxtakenotes** [comment]
no it works properly, reverb happens when the gun shoots. stop lying

**Comment by CrafterRa** [comment]
im not lying i saw and heared it is it o problem that only happens on my gmod?

**Comment by relaxtakenotes** [comment]
seems like it is

**Comment by CrafterRa** [comment]
did you try it with max payne weapons?

**Comment by relaxtakenotes** [comment]
im not gonna support obscure weapon packs

**Comment by CrafterRa** [comment]
ok understood so its the max payne weapons that have the problem

**Comment by CrafterRa** [comment]
ok im going to test some popular weapon bases
