### ISSUE TITLE
sound doesn't works on hl2

### ISSUE THREAD

**Issue by AngelinoVinz** [modusmogulus/GmodDynamicWeaponReverb#67]
hello, i already read some of the closed issues searching for a solution, but nothing worked for me so i will lend some videos bc i don't know what to do :P

https://github.com/modusmogulus/GmodDynamicWeaponReverb/assets/72633372/1fbc4af6-3ab8-4ed1-b425-e9b9b5400424

https://github.com/modusmogulus/GmodDynamicWeaponReverb/assets/72633372/89538ff4-0914-452c-a706-0a9bafa78545

https://github.com/modusmogulus/GmodDynamicWeaponReverb/assets/72633372/9979e5df-1806-449f-b350-0989d2113f54

**Comment by relaxtakenotes** [comment]
![image](https://github.com/modusmogulus/GmodDynamicWeaponReverb/assets/91839650/2646f755-708b-471e-8144-2aa92c89be2c)
this mod is likely conflicting with DWR.

**Comment by relaxtakenotes** [comment]
use this mod instead: https://steamcommunity.com/sharedfiles/filedetails/?id=2977096121
It's 100 times better, however it's still incompatible. if you ask the developer nicely he might implement a fix for other mods that rely on entityfirebullets.

**Comment by AngelinoVinz** [comment]
> ![image](https://private-user-images.githubusercontent.com/91839650/339244779-2646f755-708b-471e-8144-2aa92c89be2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzQ3NjYsIm5iZiI6MTcxODMzNDQ2NiwicGF0aCI6Ii85MTgzOTY1MC8zMzkyNDQ3NzktMjY0NmY3NTUtNzA4Yi00NzFlLTgxNDQtMmFhOTJjODliZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAzMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYmE3NzBiOGZmYmM5MGI2NmYxOGRlOTg4ZDczODliMDZhNzBjODFkMWFhYmMxOGExNjVkNjRiMjUwY2ViYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q-QhuqW_vks3u5rQnl-3_ITpftaN5EdgL6Nv2ubNG-Y) this mod is likely conflicting with DWR.

thanks for the answer, but i tried and stills not working dude, im getting upset

**Comment by relaxtakenotes** [comment]
> > ![image](https://private-user-images.githubusercontent.com/91839650/339244779-2646f755-708b-471e-8144-2aa92c89be2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzQ3NjYsIm5iZiI6MTcxODMzNDQ2NiwicGF0aCI6Ii85MTgzOTY1MC8zMzkyNDQ3NzktMjY0NmY3NTUtNzA4Yi00NzFlLTgxNDQtMmFhOTJjODliZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAzMDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYmE3NzBiOGZmYmM5MGI2NmYxOGRlOTg4ZDczODliMDZhNzBjODFkMWFhYmMxOGExNjVkNjRiMjUwY2ViYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q-QhuqW_vks3u5rQnl-3_ITpftaN5EdgL6Nv2ubNG-Y) this mod is likely conflicting with DWR.
> 
> thanks for the answer, but i tried and stills not working dude, im getting upset

it's definitely not dwr's fault. try turning off mods that can manipulate or detect bullets in any way.
